In [8]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [1]:
import bct
import pandas as pd
import numpy as np
import os
import sys

# importing and making packages관련 :
https://stackoverflow.com/a/9049246/9042297  : 왜 (처음에) import utils 한 후에 utils.load_data하면 바로 안되는지(no package found라고 뜸)
* solutions : 
    1. `__init__.py`안에다가, `from .import load_data`라고 해야한다 $\rightarrow{}$ 나는 이걸 썼다
    2. 또는, `import utils.load__data`라고 해도 된다



# 0. Importing Module/Data

In [2]:
#####IMPORTING utils module#####
## so that we can import from one directory above's utils
#https://blog.finxter.com/python-how-to-import-modules-from-another-folder/
sys.path.append("/scratch/connectome/dyhan316/TVB/REAL_RESEARCH")
sys.path

['/scratch/connectome/dyhan316/TVB/REAL_RESEARCH/Brain_Connectivity',
 '/usr/lib/python38.zip',
 '/usr/lib/python3.8',
 '/usr/lib/python3.8/lib-dynload',
 '',
 '/home/connectome/dyhan316/.local/lib/python3.8/site-packages',
 '/scratch/connectome/dyhan316/TVB/TVB_showcase/virtual_aging_showcase_copy/virtual_ageing',
 '/usr/local/lib/python3.8/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/scratch/connectome/dyhan316/TVB/REAL_RESEARCH']

In [13]:
#####IMPORTING dataset/metadata and so on#####
data_dir = '/storage/bigdata/ABCD/TVB/data'
import utils #now imports becasue it looks at the last added sys path

dataset = utils.load_data.ABCDDataset(data_dir)  #이제 된다
subjects = dataset.list_subjects()
meta_data = utils.load_metadata.metadata(data_dir)

In [14]:
##looking at some examples
print(subjects[:10])
print(dataset.load_sc(subjects[0]))
meta_data.head()

['NDARINV0X4A2LKW', 'NDARINVRERRA7FD', 'NDARINV43M1L7PL', 'NDARINV6WH2N8P4', 'NDARINVFKFN7X0T', 'NDARINVYJETWGU1', 'NDARINVNUNMDE7M', 'NDARINVPUEXNZJU', 'NDARINVCYA7HWRK', 'NDARINVPXYXMXTH']
[[ 0. 18.  1. ...  4.  0.  0.]
 [18.  0. 10. ...  0.  0.  0.]
 [ 1. 10.  0. ...  0.  0.  0.]
 ...
 [ 4.  0.  0. ...  0. 20. 47.]
 [ 0.  0.  0. ... 20.  0.  1.]
 [ 0.  0.  0. ... 47.  1.  0.]]


Age  height      weight        BMI          vol     Sex  \
ID_HBP                                                                     
NDARINVEFCVZYTR  130  56.500  118.000000  25.986060  1433652.836    Male   
NDARINVJHX361ZP  119  51.875   65.333333  17.067658  1552107.042  Female   
NDARINVNY4HU8H1  114  54.500   94.750000  22.425469  1600464.137  Female   
NDARINV22C4YKXN  111  51.000   50.500000  13.649173  1423327.367  Female   
NDARINVVX605DH1  114  52.750   70.000000  17.685137  1474259.573  Female   

                 Education  income  married  race.ethnicity  abcd_site  \
ID_HBP                                                                   
NDARINVEFCVZYTR         18       1        1               1         19   
NDARINVJHX361ZP         18       9        3               1         20   
NDARINVNY4HU8H1         18      10        3               1          9   
NDARINV22C4YKXN         18      10        1               1          9   
NDARINVVX605DH1         18       7        1               1         16   

                 morsex.1  morsex.2   ctsex.1   ctsex.2  morctsex.1  \
ID_HBP                                                                
NDARINVEFCVZYTR  0.364884  0.635116  0.897505  0.102495    0.859503   
NDARINVJHX361ZP  0.015770  0.984230  0.087163  0.912837    0.039306   
NDARINVNY4HU8H1  0.214075  0.785925  0.792755  0.207245    0.050093   
NDARINV22C4YKXN  0.185170  0.814830  0.596674  0.403326    0.455478   
NDARINVVX605DH1  0.004610  0.995390  0.003111  0.996889    0.002103   

                 morctsex.2  
ID_HBP                       
NDARINVEFCVZYTR    0.140497  
NDARINVJHX361ZP    0.960694  
NDARINVNY4HU8H1    0.949907  
NDARINV22C4YKXN    0.544522  
NDARINVVX605DH1    0.997897

LOOK AT http://localhost:11111/notebooks/TVB/TVB_showcase/virtual_aging_showcase/virtual_ageing/notebooks/1_BNM_for_resting_state.ipynb
and http://localhost:11111/notebooks/TVB/REAL_RESEARCH/Brain_Connectivity/Stella_code_BCT.ipynb
and http://localhost:11111/notebooks/TVB/virtual_aging_brain/notebooks/01_vab_github_sc_investigation.ipynb (intra-SC masking and so on이 여기다가 구현되어있다)
